# Generated by Django 4.0.2 on 2022-03-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='discripton',
            new_name='discription',
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
        migrations.AddField(
            model_name='measurement',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_measurem', to='measurement.sensor'),
        ),
    ]
